apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-app
    name: consumer
  name: contents
  namespace: kong
data:
  index.html: |
    <html>
      <head>
        <title>
          kong-apigateway sample
        </title>
      <body>
        kong-apigateway sample
      </body>
    </html>
  healthz.html: |
    <html>
      <head>
        <title>
          kong-apigateway healthz
        </title>
      <body>
        OK
      </body>
    </html>
