apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: consumer:v0.1.0
        name: consumer
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
status: {}